package com.svenjacobs.gwtbootstrap3.client.ui.constants;

/*
 * #%L
 * GwtBootstrap3
 * %%
 * Copyright (C) 2013 Sven Jacobs
 * %%
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * #L%
 */

import com.google.gwt.dom.client.Style;
import com.svenjacobs.gwtbootstrap3.client.ui.base.helper.EnumHelper;

/**
 * See glyphicons.js helper script in root folder of this module.
 *
 * @author Sven Jacobs
 */
public enum IconType implements Type, Style.HasCssName {
    ADJUST("glyphicon-adjust"),
    ALIGN_CENTER("glyphicon-align-center"),
    ALIGN_JUSTIFY("glyphicon-align-justify"),
    ALIGN_LEFT("glyphicon-align-left"),
    ALIGN_RIGHT("glyphicon-align-right"),
    ARROW_DOWN("glyphicon-arrow-down"),
    ARROW_LEFT("glyphicon-arrow-left"),
    ARROW_RIGHT("glyphicon-arrow-right"),
    ARROW_UP("glyphicon-arrow-up"),
    ASTERISK("glyphicon-asterisk"),
    BACKWARD("glyphicon-backward"),
    BAN_CIRCLE("glyphicon-ban-circle"),
    BARCODE("glyphicon-barcode"),
    BELL("glyphicon-bell"),
    BOLD("glyphicon-bold"),
    BOOK("glyphicon-book"),
    BOOKMARK("glyphicon-bookmark"),
    BRIEFCASE("glyphicon-briefcase"),
    BULLHORN("glyphicon-bullhorn"),
    CALENDAR("glyphicon-calendar"),
    CAMERA("glyphicon-camera"),
    CERTIFICATE("glyphicon-certificate"),
    CHECK("glyphicon-check"),
    CHEVRON_DOWN("glyphicon-chevron-down"),
    CHEVRON_LEFT("glyphicon-chevron-left"),
    CHEVRON_RIGHT("glyphicon-chevron-right"),
    CHEVRON_UP("glyphicon-chevron-up"),
    CIRCLE_ARROW_DOWN("glyphicon-circle-arrow-down"),
    CIRCLE_ARROW_LEFT("glyphicon-circle-arrow-left"),
    CIRCLE_ARROW_RIGHT("glyphicon-circle-arrow-right"),
    CIRCLE_ARROW_UP("glyphicon-circle-arrow-up"),
    CLOUD("glyphicon-cloud"),
    CLOUD_DOWNLOAD("glyphicon-cloud-download"),
    CLOUD_UPLOAD("glyphicon-cloud-upload"),
    COG("glyphicon-cog"),
    COLLAPSE_DOWN("glyphicon-collapse-down"),
    COLLAPSE_UP("glyphicon-collapse-up"),
    COMMENT("glyphicon-comment"),
    COMPRESSED("glyphicon-compressed"),
    COPYRIGHT_MARK("glyphicon-copyright-mark"),
    CREDIT_CARD("glyphicon-credit-card"),
    CUTLERY("glyphicon-cutlery"),
    DASHBOARD("glyphicon-dashboard"),
    DOWNLOAD("glyphicon-download"),
    DOWNLOAD_ALT("glyphicon-download-alt"),
    EARPHONE("glyphicon-earphone"),
    EDIT("glyphicon-edit"),
    EJECT("glyphicon-eject"),
    ENVELOPE("glyphicon-envelope"),
    EURO("glyphicon-euro"),
    EXCLAMATION_SIGN("glyphicon-exclamation-sign"),
    EXPAND("glyphicon-expand"),
    EXPORT("glyphicon-export"),
    EYE_CLOSE("glyphicon-eye-close"),
    EYE_OPEN("glyphicon-eye-open"),
    FACETIME_VIDEO("glyphicon-facetime-video"),
    FAST_BACKWARD("glyphicon-fast-backward"),
    FAST_FORWARD("glyphicon-fast-forward"),
    FILE("glyphicon-file"),
    FILM("glyphicon-film"),
    FILTER("glyphicon-filter"),
    FIRE("glyphicon-fire"),
    FLAG("glyphicon-flag"),
    FLASH("glyphicon-flash"),
    FLOPPY_DISK("glyphicon-floppy-disk"),
    FLOPPY_OPEN("glyphicon-floppy-open"),
    FLOPPY_REMOVE("glyphicon-floppy-remove"),
    FLOPPY_SAVE("glyphicon-floppy-save"),
    FLOPPY_SAVED("glyphicon-floppy-saved"),
    FOLDER_CLOSE("glyphicon-folder-close"),
    FOLDER_OPEN("glyphicon-folder-open"),
    FONT("glyphicon-font"),
    FORWARD("glyphicon-forward"),
    FULLSCREEN("glyphicon-fullscreen"),
    GBP("glyphicon-gbp"),
    GIFT("glyphicon-gift"),
    GLASS("glyphicon-glass"),
    GLOBE("glyphicon-globe"),
    HAND_DOWN("glyphicon-hand-down"),
    HAND_LEFT("glyphicon-hand-left"),
    HAND_RIGHT("glyphicon-hand-right"),
    HAND_UP("glyphicon-hand-up"),
    HDD("glyphicon-hdd"),
    HD_VIDEO("glyphicon-hd-video"),
    HEADER("glyphicon-header"),
    HEADPHONES("glyphicon-headphones"),
    HEART("glyphicon-heart"),
    HEART_EMPTY("glyphicon-heart-empty"),
    HOME("glyphicon-home"),
    IMPORT("glyphicon-import"),
    INBOX("glyphicon-inbox"),
    INDENT_LEFT("glyphicon-indent-left"),
    INDENT_RIGHT("glyphicon-indent-right"),
    INFO_SIGN("glyphicon-info-sign"),
    ITALIC("glyphicon-italic"),
    LEAF("glyphicon-leaf"),
    LINK("glyphicon-link"),
    LIST("glyphicon-list"),
    LIST_ALT("glyphicon-list-alt"),
    LOCK("glyphicon-lock"),
    LOG_IN("glyphicon-log-in"),
    LOG_OUT("glyphicon-log-out"),
    MAGNET("glyphicon-magnet"),
    MAP_MARKER("glyphicon-map-marker"),
    MINUS("glyphicon-minus"),
    MINUS_SIGN("glyphicon-minus-sign"),
    MOVE("glyphicon-move"),
    MUSIC("glyphicon-music"),
    NEW_WINDOW("glyphicon-new-window"),
    OFF("glyphicon-off"),
    OK("glyphicon-ok"),
    OK_CIRCLE("glyphicon-ok-circle"),
    OK_SIGN("glyphicon-ok-sign"),
    OPEN("glyphicon-open"),
    PAPERCLIP("glyphicon-paperclip"),
    PAUSE("glyphicon-pause"),
    PENCIL("glyphicon-pencil"),
    PHONE("glyphicon-phone"),
    PHONE_ALT("glyphicon-phone-alt"),
    PICTURE("glyphicon-picture"),
    PLANE("glyphicon-plane"),
    PLAY("glyphicon-play"),
    PLAY_CIRCLE("glyphicon-play-circle"),
    PLUS("glyphicon-plus"),
    PLUS_SIGN("glyphicon-plus-sign"),
    PRINT("glyphicon-print"),
    PUSHPIN("glyphicon-pushpin"),
    QRCODE("glyphicon-qrcode"),
    QUESTION_SIGN("glyphicon-question-sign"),
    RANDOM("glyphicon-random"),
    RECORD("glyphicon-record"),
    REFRESH("glyphicon-refresh"),
    REGISTRATION_MARK("glyphicon-registration-mark"),
    REMOVE("glyphicon-remove"),
    REMOVE_CIRCLE("glyphicon-remove-circle"),
    REMOVE_SIGN("glyphicon-remove-sign"),
    REPEAT("glyphicon-repeat"),
    RESIZE_FULL("glyphicon-resize-full"),
    RESIZE_HORIZONTAL("glyphicon-resize-horizontal"),
    RESIZE_SMALL("glyphicon-resize-small"),
    RESIZE_VERTICAL("glyphicon-resize-vertical"),
    RETWEET("glyphicon-retweet"),
    ROAD("glyphicon-road"),
    SAVE("glyphicon-save"),
    SAVED("glyphicon-saved"),
    SCREENSHOT("glyphicon-screenshot"),
    SD_VIDEO("glyphicon-sd-video"),
    SEARCH("glyphicon-search"),
    SEND("glyphicon-send"),
    SHARE("glyphicon-share"),
    SHARE_ALT("glyphicon-share-alt"),
    SHOPPING_CART("glyphicon-shopping-cart"),
    SIGNAL("glyphicon-signal"),
    SORT("glyphicon-sort"),
    SORT_BY_ALPHABET("glyphicon-sort-by-alphabet"),
    SORT_BY_ALPHABET_ALT("glyphicon-sort-by-alphabet-alt"),
    SORT_BY_ATTRIBUTES("glyphicon-sort-by-attributes"),
    SORT_BY_ATTRIBUTES_ALT("glyphicon-sort-by-attributes-alt"),
    SORT_BY_ORDER("glyphicon-sort-by-order"),
    SORT_BY_ORDER_ALT("glyphicon-sort-by-order-alt"),
    SOUND_5_1("glyphicon-sound-5-1"),
    SOUND_6_1("glyphicon-sound-6-1"),
    SOUND_7_1("glyphicon-sound-7-1"),
    SOUND_DOLBY("glyphicon-sound-dolby"),
    SOUND_STEREO("glyphicon-sound-stereo"),
    STAR("glyphicon-star"),
    STAR_EMPTY("glyphicon-star-empty"),
    STATS("glyphicon-stats"),
    STEP_BACKWARD("glyphicon-step-backward"),
    STEP_FORWARD("glyphicon-step-forward"),
    STOP("glyphicon-stop"),
    SUBTITLES("glyphicon-subtitles"),
    TAG("glyphicon-tag"),
    TAGS("glyphicon-tags"),
    TASKS("glyphicon-tasks"),
    TEXT_HEIGHT("glyphicon-text-height"),
    TEXT_WIDTH("glyphicon-text-width"),
    TH("glyphicon-th"),
    THUMBS_DOWN("glyphicon-thumbs-down"),
    THUMBS_UP("glyphicon-thumbs-up"),
    TH_LARGE("glyphicon-th-large"),
    TH_LIST("glyphicon-th-list"),
    TIME("glyphicon-time"),
    TINT("glyphicon-tint"),
    TOWER("glyphicon-tower"),
    TRANSFER("glyphicon-transfer"),
    TRASH("glyphicon-trash"),
    TREE_CONIFER("glyphicon-tree-conifer"),
    TREE_DECIDUOUS("glyphicon-tree-deciduous"),
    UNCHECKED("glyphicon-unchecked"),
    UPLOAD("glyphicon-upload"),
    USD("glyphicon-usd"),
    USER("glyphicon-user"),
    VOLUME_DOWN("glyphicon-volume-down"),
    VOLUME_OFF("glyphicon-volume-off"),
    VOLUME_UP("glyphicon-volume-up"),
    WARNING_SIGN("glyphicon-warning-sign"),
    WRENCH("glyphicon-wrench"),
    ZOOM_IN("glyphicon-zoom-in"),
    ZOOM_OUT("glyphicon-zoom-out");

    private final String cssClass;

    private IconType(final String cssClass) {
        this.cssClass = cssClass;
    }

    @Override
    public String getCssName() {
        return cssClass;
    }

    public static IconType fromStyleName(final String styleName) {
        return EnumHelper.fromStyleName(styleName, IconType.class, null);
    }
}
